### ISSUE TITLE
Failed to activate the marked package

### ISSUE THREAD

**Issue by blomma** [cliffrowley/atom-marked#6]
1. Start Atom

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [marked](https://github.com/cliffrowley/atom-marked) package, v0.1.7

### Stack Trace

Failed to activate the marked package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/blomma/.atom/packages/marked/lib/marked.coffee:14:32)
    at Package.module.exports.Package.activateNow (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/blomma/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "wrap-guide",
      "git-diff",
      "background-tips"
    ],
    "themes": [
      "isotope-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/Users/blomma/Dropbox/Projects/private",
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
comment-headers, v2.6.0
file-icons, v1.5.4
indentation-indicator, v0.4.1
isotope-ui, v2.1.1
language-cshtml, v0.1.1
language-fish-shell, v1.0.2
language-lua, v0.9.2
language-powershell, v2.0.0
language-swift, v0.4.0
linter, v0.12.1
linter-coffeelint, v0.2.1
marked, v0.1.7
one-tab, v0.4.0
soft-wrap-indicator, v0.5.1
tasks, v2.0.0
the-closer, v0.5.0

# Dev
No dev packages
```

**Comment by cliffrowley** [comment]
Hey there, sorry I don't seem to be able to replicate this.  Are you still having this issue?

**Comment by blomma** [comment]
Nope, I'm no longer getting this error, so you I'm marking it as closed :)
